/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'


export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={1000} decay={2} position={[4.076, 5.904, -1.005]} rotation={[-1.839, 0.602, 1.932]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={22.895} position={[7.359, 4.958, 6.926]} rotation={[-0.627, 0.71, 0.441]} />
      <mesh geometry={nodes.innerstar.geometry} material={materials.innergradient} position={[0.022, 1, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[5.33, 8.24, 5.33]} />
      <mesh geometry={nodes.Outer_STar.geometry} material={materials.outergradient} position={[0, 1, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[10, 10, 10]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
